name: test

on:
  push:
    branches:
      - dev
      - "*upstream*"
  pull_request:
    branches:
      - dev
      - "*upstream*"

concurrency:
  cancel-in-progress: true
  group: ${{github.workflow}}-${{github.ref}}

env:
  CARGO_TERM_COLOR: always
  TARGET_RUST_VERSION: "stable"

jobs:
  check-ci-install:
    name: CI install
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install foundry-zksync
        run: cp ./install-foundry-zksync ./foundryup-zksync/* /tmp/ && cd /tmp && ./install-foundry-zksync
      - name: Verify installation
        run: forge --version

  check-ci-install-anvil:
    name: CI install anvil-zksync
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install foundry-zksync
        run: |
          cp ./install-foundry-zksync ./foundryup-zksync/* /tmp/
          cd /tmp
          ./install-foundry-zksync
      
      - name: Verify anvil-zksync installation
        run: anvil-zksync --version
