name: test

on:
  push:
    branches:
      - dev
      - "*upstream*"
  pull_request:
    branches:
      - dev
      - "*upstream*"

concurrency:
  cancel-in-progress: true
  group: ${{github.workflow}}-${{github.ref}}

env:
  CARGO_TERM_COLOR: always
  TARGET_RUST_VERSION: "stable"

jobs:
  check-ci-install:
    name: CI install
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install foundry-zksync
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path C:/Temp/
          Get-ChildItem ./foundryup-zksync/ | ForEach-Object { Copy-Item $_.FullName -Destination C:/Temp/ -Force }
          Copy-Item ./install-foundry-zksync -Destination C:/Temp/ -Force
          cd C:/Temp/
          ./install-foundry-zksync
      
      - name: Debug Temp Directory
        shell: pwsh
        run: Get-ChildItem C:/Temp/ -Recurse

      - name: Add forge to PATH
        shell: pwsh
        run: $env:PATH += ";C:/Temp/"; Write-Output $env:PATH

      - name: Verify installation
        shell: pwsh
        run: forge --version

  check-ci-install-anvil:
    name: CI install anvil-zksync
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install foundry-zksync
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path C:/Temp/
          Get-ChildItem ./foundryup-zksync/ | ForEach-Object { Copy-Item $_.FullName -Destination C:/Temp/ -Force }
          Copy-Item ./install-foundry-zksync -Destination C:/Temp/ -Force
          cd C:/Temp/
          ./install-foundry-zksync

      - name: Verify anvil-zksync installation
        shell: pwsh
        run: anvil-zksync --version


